.include "macro.inc"

.section .sdata, "wa"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_800E6A8C

dlabel D_800E6A8C
    /* D728C 800E6A8C 00004000 */ .word 0x00400000
enddlabel D_800E6A8C

nonmatching D_800E6A90

dlabel D_800E6A90
    /* D7290 800E6A90 */ .short 0x0000
    /* D7292 800E6A92 */ .short 0x0000
enddlabel D_800E6A90

nonmatching D_800E6A94

dlabel D_800E6A94
    /* D7294 800E6A94 00000000 */ .word 0x00000000
enddlabel D_800E6A94

nonmatching D_800E6A98

dlabel D_800E6A98
    /* D7298 800E6A98 */ .short 0x0000
enddlabel D_800E6A98

nonmatching D_800E6A9A

dlabel D_800E6A9A
    /* D729A 800E6A9A */ .short 0x0000
enddlabel D_800E6A9A

nonmatching D_800E6A9C

dlabel D_800E6A9C
    /* D729C 800E6A9C 00000000 */ .word 0x00000000
enddlabel D_800E6A9C

nonmatching D_800E6AA0

dlabel D_800E6AA0
    /* D72A0 800E6AA0 */ .short 0x000C
enddlabel D_800E6AA0

nonmatching D_800E6AA2

dlabel D_800E6AA2
    /* D72A2 800E6AA2 */ .short 0x000C
    /* D72A4 800E6AA4 */ .short 0x0000
    /* D72A6 800E6AA6 */ .short 0x0000
    /* D72A8 800E6AA8 */ .short 0x0000
    /* D72AA 800E6AAA */ .short 0x0000
enddlabel D_800E6AA2

nonmatching D_800E6AAC

dlabel D_800E6AAC
    /* D72AC 800E6AAC 00000000 */ .word 0x00000000
enddlabel D_800E6AAC

nonmatching D_800E6AB0

dlabel D_800E6AB0
    /* D72B0 800E6AB0 02000000 */ .word 0x00000002
enddlabel D_800E6AB0

nonmatching D_800E6AB4

dlabel D_800E6AB4
    /* D72B4 800E6AB4 00000000 */ .word 0x00000000
    /* D72B8 800E6AB8 */ .short 0x0001
enddlabel D_800E6AB4

nonmatching D_800E6ABA

dlabel D_800E6ABA
    /* D72BA 800E6ABA */ .short 0x0000
enddlabel D_800E6ABA

nonmatching D_800E6ABC

dlabel D_800E6ABC
    /* D72BC 800E6ABC */ .short 0x001F
    /* D72BE 800E6ABE */ .short 0x0000
enddlabel D_800E6ABC
