name: ENTER.BIN
sha1: a7946495e695a25606c865aefe53d515d8cf1dda

options:
  basename: enter
  base_path: ../..
  target_path: extracted/modules/ENTER.BIN
  elf_path: build/overlays/enter/enter.elf
  platform: psx
  compiler: PSYQ

  asm_path: asm/overlays/enter
  src_path: src/overlays/enter
  build_path: build/overlays/enter
  generated_asm_macros_directory: include

  ld_script_path: config/overlays/enter.ld
  ld_dependencies: true
  find_file_boundaries: false
  gp_value: 0x800E6A8C

  o_as_suffix: true
  use_legacy_include_asm: false
  ld_align_section_vram_end: false
  ld_align_segment_vram_end: false
  subalign: 2

  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  symbol_addrs_path:
    - config/symbol_addrs.txt
  undefined_funcs_auto_path: config/overlays/enter.undefined_funcs_auto.txt
  undefined_syms_auto_path: config/overlays/enter.undefined_syms_auto.txt

  string_encoding: SHIFT_JIS
  data_string_encoding: SHIFT_JIS
  rodata_string_guesser_level: 0
  data_string_guesser_level: 0

# Exact live match at 0x80188F78 during exhibition setup.
segments:
  - name: enter
    type: code
    start: 0x0
    vram: 0x80188F78
    subsegments:
      - [0x0, rodata]
      - [0x604, c]
      - [0x6E64, data]
      - [0xB784]
  - [0xB784]
