name: SELFORM.BIN
sha1: 95651f110448e163b81b0dfa44636ed8efd2be02

options:
  basename: selform
  base_path: ../..
  target_path: extracted/modules/SELFORM.BIN
  elf_path: build/overlays/selform/selform.elf
  platform: psx
  compiler: PSYQ

  asm_path: asm/overlays/selform
  src_path: src/overlays/selform
  build_path: build/overlays/selform
  generated_asm_macros_directory: include

  ld_script_path: config/overlays/selform.ld
  ld_dependencies: true
  find_file_boundaries: false
  gp_value: 0x800E6A8C

  o_as_suffix: true
  use_legacy_include_asm: false
  ld_align_section_vram_end: false
  ld_align_segment_vram_end: false
  subalign: 2

  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  symbol_addrs_path:
    - config/symbol_addrs.txt
  undefined_funcs_auto_path: config/overlays/selform.undefined_funcs_auto.txt
  undefined_syms_auto_path: config/overlays/selform.undefined_syms_auto.txt

  string_encoding: SHIFT_JIS
  data_string_encoding: SHIFT_JIS
  rodata_string_guesser_level: 0
  data_string_guesser_level: 0

# Exact live match at 0x8011D800 on the formation screen.
segments:
  - name: selform
    type: code
    start: 0x0
    vram: 0x8011D800
    subsegments:
      - [0x0, rodata]
      - [0x2C, c]
      - [0x4484, data]
      - [0x584C]
  - [0x584C]
