.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 3
nonmatching jtbl_80138000

dlabel jtbl_80138000
    /* 0 80138000 84861380 */ .word .L80138684
    /* 4 80138004 84861380 */ .word .L80138684
    /* 8 80138008 84861380 */ .word .L80138684
    /* C 8013800C FC861380 */ .word .L801386FC
    /* 10 80138010 FC861380 */ .word .L801386FC
    /* 14 80138014 10871380 */ .word .L80138710
enddlabel jtbl_80138000
