.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 3
nonmatching jtbl_8011D800

dlabel jtbl_8011D800
    /* 0 8011D800 FCE51180 */ .word .L8011E5FC
    /* 4 8011D804 0CE61180 */ .word .L8011E60C
    /* 8 8011D808 FCE51180 */ .word .L8011E5FC
    /* C 8011D80C FCE51180 */ .word .L8011E5FC
    /* 10 8011D810 6CE61180 */ .word .L8011E66C
    /* 14 8011D814 00000000 */ .word 0x00000000
enddlabel jtbl_8011D800

.align 3
nonmatching jtbl_8011D818

dlabel jtbl_8011D818
    /* 18 8011D818 84E71180 */ .word .L8011E784
    /* 1C 8011D81C C0E71180 */ .word .L8011E7C0
    /* 20 8011D820 84E71180 */ .word .L8011E784
    /* 24 8011D824 84E71180 */ .word .L8011E784
    /* 28 8011D828 14E71180 */ .word .L8011E714
enddlabel jtbl_8011D818
